### PR TITLE
This adds the multipolygon type classes to doctrine2-spacial

### PR DESCRIPTION
**Pull request by ibedouglas**
This adds the multipolygon type classes to doctrine2-spacial. Previously the included type was failing.  

Add using the multipolygon type using following code:
Type::addType('multipolygon', 'CrEOF\Spatial\DBAL\Types\Geometry\MultiPolygonType');

### CODE REVIEW

**Comment by collmomo** [comment]
Hey, I am not sure how to point my composer.json to your updated branch version, I tried 
 "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/djlambert/doctrine2-spatial"
        }
    ], 
"require": {
        "creof/doctrine2-spatial": "dev-master"
    }
by following https://getcomposer.org/doc/05-repositories.md
However, its still not working, what is the name of your version ?

**Comment by holtkamp** [comment]
desperate one year bump on this PR @djlambert

**Comment by holtkamp** [comment]
@ibedouglas note that your implementation is incomplete. The https://github.com/honestbuildings/doctrine2-spatial/blob/0.0.2/lib/CrEOF/Spatial/PHP/Types/AbstractMultiPolygon.php file is a copy-paste of the plain AbstractPolygon. 

@amenadiel seems to have implemented the proper functionality in https://github.com/djlambert/doctrine2-spatial/pull/33 with https://github.com/amenadiel/doctrine2-spatial/commit/ca984de96463d8106eb3bd183b5722bed5135995

**Comment by sadortun** [comment]
@ibedouglas Please have a look at the Multipolygon  in [develop](https://github.com/creof/doctrine2-spatial/tree/develop) branch. 

If there is something i missed, please let me know.

Thanks,
Samuel

**Pull request closed without merging**
