### PR TITLE
Map Geography Database Types and Unify Platforms

### PR DESCRIPTION
**Pull request by djlambert**
Added getMappedDatabaseTypes() method to PlatformInterface to enable platforms supporting both Geometry and Geography types to map each independently. This removes the previous restriction of using one class (geom/geo) of a spatial datatype at a time. Updated schema tests to properly test this.

Add an additional test for passing the default SRID through the column declaration.

Cleanup and simplify how tests specify which entities it uses. Now a single constant is used in the test and base test classes.

Removed static exception methods. Only one or two of them were being used in more than one place.

And lastly, move database platform classes out from the Types namespace and unify the Geometry and Geography platforms into a single class for each database platform. Changes were made to the PlatformInterface, but it is not currently a public (documented) API. This made it very obvious that the current SRID handling is broken, but I wanted all existing tests to pass at least until the PHP objects are moved out of the library.

### CODE REVIEW

**Comment by djlambert** [comment]
This is a bigger PR than I'd like but it all seemed related. Depending on what the Code Coverage reports say I might like to push some more tests.

**Comment by ddproxy** [comment]
This is awesome. I'm going to test this code a little but tonight or tomorrow morning but it looks great.

**Comment by djlambert** [comment]
Please do! It's some pretty significant surgery.

**Comment by djlambert** [comment]
Nice! +11% coverage after that last push.

**Comment by djlambert** [comment]
Now it does what it's supposed to. I didn't put a ```@group``` annotation in ```SchemaTest``` so the test was never being run. The configs are only defining excludes now to avoid this in the future.

**Comment by djlambert** [comment]
Much better.

coverage/coveralls — Coverage increased (+11.7%) to 93.333%

**Comment by djlambert** [comment]
@ddproxy have you had a chance to do any testing with this?

**Comment by ddproxy** [comment]
I've been getting up to date with 1.0 - once I have a few bugs worked out in the rest of the application I'm checking this out.

**Comment by djlambert** [comment]
Thinking we probably want to tag 1.0.1 before merging this too.

**Comment by ddproxy** [comment]
Agreed - and tag the next one 1.1?

Lets tag then merge this. I'm done playing with this.

**Comment by djlambert** [comment]
Sounds good!

**Pull request merged**
