### PR TITLE
Pull request to test value before using function ctype

### LINKED ISSUE #207: Trying to access array offset on value of type resource
I'm not sure why, on my dev machine, with an env under docker I had suddenly this error today : "Trying to access array offset on value of type resource"

It looks like modifying line 138 of `lib/CrEOF/Spatial/DBAL/Types/AbstractSpatialType.php` like so fixes the error, but I'm not sure why nor where to look for an explanation : 

```php
if (!is_resource($value) && ctype_alpha($value[0])) {
```

If I can be of any help, please give hints to where to look, and what is missing in this issue description :)

### PR DESCRIPTION
**Pull request by Alexandre-T**
This pull request ws created to Fix #207. But when I saw the reports of codeclimat, the problem with travis, I decided to fork the project to purpose a new release of doctrine2-spatial which can works with the current PHP versions and doctrine versions.

### CODE REVIEW

**Comment by holtkamp** [comment]
Great job working on a new fork, also got some change in my fork which might be useful, will have a look after my vacation ;)

**Comment by Alexandre-T** [comment]
I close this pull request, because my fork will create some BC incompatibility, but i will submit a pull request for a next major version when upgrade will be done.

**Comment by Alexandre-T** [comment]
Hello @holtkamp , I have published a [2.0.0-rc.0 version](https://github.com/Alexandre-T/doctrine2-spatial/tree/2.0.0-rc.0). If you want, you can test it and install it via composer (Be careful to specify the 2.0.0-rc.0 version)

```
composer require "alexandret/doctrine2-spatial:2.0.0-rc.0"
```

A full documentation can be found here: https://doctrine2-spatial.readthedocs.io/en/latest/

Please forgive me, I'm not fluent in english.

**Comment by holtkamp** [comment]
Great work @Alexandre-T, will try to have a look coming weeks and report my findings.

**Pull request closed without merging**
